name: Run Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "2.7"
            tox-env: py27
          - python-version: "3.6"
            tox-env: py36
          - python-version: "3.7"
            tox-env: py37,docs,readme,black
          - python-version: "3.8"
            tox-env: py38
          - python-version: "3.9"
            tox-env: py39
          - python-version: "3.10"
            tox-env: py310
          - python-version: "pypy3"
            tox-env: pypy3
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install tox
    - name: Install coveralls dependencies
      if: ${{ matrix.python-version != '2.7' }}
      run: |
        python -m pip install coveralls coverage-lcov toml
    - name: Execute tests with tox
      env:
        TOXENV: ${{ matrix.tox-env }}
      run: |
        tox
    - name: Coverage format into lcov
      if: ${{ matrix.python-version != '2.7' }}
      run: |
        coverage-lcov --output_file_path lcov.info
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@1.1.3
      if: ${{ matrix.python-version != '2.7' }}
      with:
        github-token: ${{ secrets.github_token }}
        flag-name: run-${{ matrix.python-version }}
        path-to-lcov: lcov.info
        parallel: true
  finish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: lcov.info
        parallel-finished: true
